---

- name: Set test id
  set_fact: test_id={{ ansible_date_time|to_uuid }}

- name: Set URL
  set_fact: test_url={{ url }}/?test={{ test_id }}

- block:
  - name: Verify URL
    register: url_verify
    retries: '{{ timeout|default(60) }}'
    delay: 1
    until: url_verify.failed == false
    changed_when: false
    shell: curl -I {% if url.startswith('https') and 'staging' in acme %} -k {% endif %} {{ test_url }}

  - include_role: name=yourlabs.remember
    vars:
      remember_extra: {state: success}

  always:
  - name: Show traefik container logs
    shell: docker logs --tail=30 traefik
    changed_when: false

  - block:
    - name: Get password to enter <url> with user root
      shell: cat /root/password_root
      changed_when: false
      register: password_root

    - name: Dashboard URL {{ url.replace('//', '//root:' + password_root.stdout.strip() + '@') }}
      debug: msg="If you have a password, it is shown here"
    when: password != 'none'
