---

- name: Ensure docker was setup once on this host
  include_role: name=yourlabs.roleonce
  vars:
    rolenames: [yourlabs.docker]

- name: Install passlib library for ansible htpasswd module
  pip:
    name: passlib
    state: present

- name: Fetch password_root if any
  fetch:
    src: /root/password_root
    dest: password_root
    flat: true
  failed_when: false

- name: Create /etc/traefik/htpasswd
  with_items: ['', '/htpasswd']
  file:
    path: /etc/traefik{{ item }}
    state: directory
    owner: root
    mode: 0755

- name: Generate htpasswd file
  htpasswd:
    password: "{{ lookup('password', 'password_root chars=ascii_letters length=32') }}"
    path: /etc/traefik/htpasswd/root
    name: root

- name: Generate /etc/traefik/traefik.toml
  template:
    src: traefik.toml
    dest: /etc/traefik/traefik.toml
    mode: 0644
    owner: root

- name: Create web network
  docker_network:
    name: web

- name: Create traefik container
  docker_container:
    pull: true
    restart: true
    name: traefik
    image: '{{ image }}'
    published_ports: ['80:80', '443:443']
    exposed_ports: 8080
    restart_policy: always
    log_driver: '{{ log_driver }}'
    volumes:
    - /etc/traefik/traefik.toml:/traefik.toml:ro
    - /etc/traefik/htpasswd:/htpasswd:ro
    - /etc/traefik/acme:/etc/traefik/acme:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - name: web
    command: --docker --web
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:traefik.{{ domain }}'
      traefik.frontend.auth.basic.usersFile: '/htpasswd/root'
      traefik.frontend.auth.basic.removeHeader: 'true'
      traefik.port: '8080'

- name: Upload password in /root/password_root
  copy:
    src: password_root
    dest: /root/password_root
    owner: root
    mode: 0600

- name: Remove local copy of password_root and htaccess
  changed_when: false
  file:
    path: '{{ item }}'
    state: absent
  with_items:
  - password_root
  - ./.tmp_traefik_htaccess

- name: Save facts for further runs
  shell:
    cmd: |
      cat > /etc/ansible/facts.d/yourlabs_traefik.fact << EOF
      #!/bin/sh
      echo '{
        "traefik_domain": "{{ domain }}",
        "traefik_acme": "{{ acme }}",
        "traefik_email": "{{ email }}",
        "yourlabs_traefik": "installed"
      }'
      EOF

- name: Make facts executable for Ansible
  file: path=/etc/ansible/facts.d/yourlabs_traefik.fact mode=0755

- name: Show traefik container logs
  shell: docker logs --tail=30 traefik
  changed_when: false

- name: Show password to enter https://traefik.<domain> with user root
  shell: cat /root/password_root
  changed_when: false
