debug = true

logLevel = "{{ logLevel }}"
defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    #sniStrict = true
    #minVersion = "VersionTLS12"
    #cipherSuites = [
    #  "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    #  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    #  "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
    #  "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
    #  "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    #  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    #  "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
    #]

  [entryPoint.http]
  address = ":80"
    [entryPoint.http.redirect]
    entryPoint = "https"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
network = "web"

[acme]
email = "{{ email }}"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true
{% if acme == 'staging' %}
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
{% else %}
caServer = "https://acme-v02.api.letsencrypt.org/directory"
{% endif %}
  [acme.tlsChallenge]
  #[acme.httpChallenge]
  #entryPoint = "https"

[frontend]
rule = "Host:traefik.{{ domain }}"
entryPoint = "http"
